# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('vk', models.BigIntegerField()),
                ('fb', models.BigIntegerField()),
            ],
        ),
    ]
