# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk',
            field=models.BigIntegerField(null=True),
        ),
    ]
